### ISSUE TITLE
Still having the issue with longClassPath

### ISSUE THREAD

**Issue by pbehl80** [viswaramamoorthy/gradle-util-plugins#7]
I am still having issue with Long Classpath after applying the plugin
java.io.IOException: Cannot run program "java": CreateProcess error=206, The filename or extension is too long
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.ford.auto.parallel.runtime.ParallelFeatureRunner.run(ParallelFeatureRunner.java:27)
	at com.ford.auto.parallel.runtime.ParallelRunner.runFeature(ParallelRunner.java:143)
	at com.ford.auto.parallel.runtime.ParallelRunner.lambda$0(ParallelRunner.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vai21** [comment]
I use this script

`buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.com.github.viswaramamoorthy:gradle-util-plugins:0.1.0-RELEASE"
  }
}

apply plugin: "com.github.ManifestClasspath"`

It works..
maybe try to clean build..

**Comment by gitanjali6** [comment]
Hello,
I tried to use this gradle-util-plugins plugin, I can see it downloaded in .gradle cache but, still getting classpath issue while running on windows. Can you tell me the location where it creates the manifest jar ? and check whether it sets the classpath with this manifest jar or not?
I am simply using below scripts in build.gradle:

buildscript {
repositories {
maven {
url "https://plugins.gradle.org/m2/"
}
}
dependencies {
classpath "gradle.plugin.com.github.viswaramamoorthy:gradle-util-plugins:0.1.0-RELEASE"
}
}

apply plugin: "com.github.ManifestClasspath"
